### ISSUE TITLE
Mahout : fix the vocabulary size

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/behemoth#19]
See http://osdir.com/ml/general/2011-04/msg00949.html

/////////////////////////////////////////////////////////////

Note that you probably need to introduce an "OTHER" token so that you can
fix the vocabulary size.

Otherwise, hashed representations will let you have an open vocabulary but
still have a fixed feature vector size.

**Comment by jnioche** [comment]
@smarthi since you are a Mahout expert, is this still an issue and if so how could it be fixed?

**Comment by smarthi** [comment]
This is highly irrelevant today given the present state of Mahout

**Comment by jnioche** [comment]
Ok, closing then. Thanks
