### ISSUE TITLE
Upgrade to Mahout 0.10.0

### ISSUE THREAD

**Issue by lewismc** [DigitalPebble/behemoth#54]
As suggested by @jnioche an upgrade to Mahout 0.10 would be nice.
FYI, Mahout have implemented profiles dealing with Hadoop 1.2.1 and 2.X as of Hadoop 0.10 so this is certainly possible without polluting too much of the behemoth-mahout module.
I'll get to work on this when I can.

**Comment by smarthi** [comment]
@lewismc Mahout's presently at 0.12.2 and we have completely eliminated Hadoop 1.x profiles and now support HAdoop 2x, Spark 1.6.2, Flink 1.1.3.  Are u still working on this? I met Julian in Seville last week and I can take a crack at this.

**Comment by lewismc** [comment]
Please do. Behemoth is a very useful framework. Please do Sir.

**Comment by jnioche** [comment]
Superseded by #62
