### ISSUE TITLE
CorpusGenerator never invokes document.setText

### ISSUE THREAD

**Issue by ppedemon** [DigitalPebble/behemoth#57]
I was trying to use the UIMA module with a text corpus without success (stuff that *should* have been annotated wasn't). After some inspection of the source code, I found that the problem was that [CorpusGenerator](https://github.com/DigitalPebble/behemoth/blob/master/core/src/main/java/com/digitalpebble/behemoth/util/CorpusGenerator.java) never calls `setText`, using instead exclusively `setContent`. The catch here is that [UIMAMapper](https://github.com/DigitalPebble/behemoth/blob/master/uima/src/main/java/com/digitalpebble/behemoth/uima/UIMAMapper.java#L91) silently (unless you adjust the log levels so debug messages are emitted) discards documents with null text.

I have... fixed? this problem by adding two new options to CorpusGenerator: 
  1. mode, text or binary. Text mode uses setText, binary mode calls setContent
  2. charset, defaults to UTF-8. Used to transform read input byte arrays to text

I don't know if I'm using behemoth the wrong way or this is a genuine issue. If the latter, you might be interested in a pull request.

**Comment by ppedemon** [comment]
Moot issue, Tika does the needed text processing.

**Comment by jnioche** [comment]
Late reply, just back from holidays. 

You are right, the Tika module does the conversion from content to text, charset identification etc... It could make sense to add an option to populate the text content within the CorpusGenerator as you suggested, this would be useful for users who have a collection of plain text files and would make things a bit simpler.

Feel free to send a PR if you have the time and inclination to add this functionality. Thanks!
